// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project01.Data;

#nullable disable

namespace Project01.Migrations
{
    [DbContext(typeof(Project01DbContext))]
    [Migration("20240807204101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Project01.Data.SearchQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SearchTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SearchQueries");
                });
#pragma warning restore 612, 618
        }
    }
}
